class AppDummyText {
  final String dummyArticleTitle =
      "Antibiotics are drugs to treat or prevent bacterial infection";
  final String dummyArticle =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pellentesque enim odio, in elementum urna tempus feugiat. Cras vel lacus a dui ullamcorper sagittis. Mauris suscipit vel enim a consectetur. Sed enim felis, ullamcorper vitae dictum sed, eleifend vehicula urna. Curabitur volutpat congue lectus, ac aliquet velit pulvinar non. Nulla volutpat magna viverra lacus convallis, et facilisis nunc gravida. In hac habitasse platea dictumst. Ut sed laoreet eros, ac vehicula magna. Vestibulum mattis ultricies faucibus. Duis finibus lectus eu ullamcorper dapibus. Maecenas turpis tortor, blandit vehicula elit a, interdum varius justo. Donec rutrum pretium malesuada. Nunc at gravida neque. Aliquam ut arcu et purus placerat dictum.\n\nInteger posuere nisl sed erat mollis, sit amet dignissim tortor pulvinar. Donec vel sollicitudin purus. Etiam maximus pulvinar ante, ac semper arcu egestas quis. Duis aliquam mollis dolor ut dictum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam aliquam lectus non neque vestibulum imperdiet. Suspendisse potenti. Etiam non libero augue. Vivamus vitae orci aliquam, placerat ipsum quis, imperdiet lacus. Suspendisse eget varius risus. Duis tortor sem, ullamcorper eget leo ac, laoreet semper leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\n\nUt sollicitudin porta condimentum. Praesent sed ex consectetur nunc dictum blandit et a arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec ipsum lectus, fringilla eget odio vel, dapibus luctus velit. Nam neque nulla, commodo at porttitor et, ornare in velit. Pellentesque venenatis ultricies nunc, id dignissim tellus commodo nec. Nunc quis enim finibus, commodo felis euismod, fermentum neque. Mauris vitae consequat ex. Duis egestas magna nec urna elementum pretium. Pellentesque tristique eleifend ex, in luctus nisi volutpat ac. Aliquam elementum egestas erat, non molestie ex consectetur vel.";
  final String dummyDrugTitle = "Bodrex Migra";
  final String dummyDrugDesc =
      "Bodrex migra merupakan obat kaplet yang mengandung paracetamol, propyphenazone, dan kafein yang dapat digunakan untuk meringankan sakit kepala. Kandungan dari obat ini juga dapat digunakan untuk meredakan sakit ringan hingga sedang hingga menurunkan demam. Obat ini akan bekerja pada pusat pengontrol suhu tubuh di bagian otak dan mengurangi produksi prostaglandin, sehingga dapat menurunkan suhu tubuh saat demam dan meredakan nyeri. Obat ini dapat dibeli pada apotek-apotek terdekat. Namun, obat ini masih belum diproduksi secara teerbatas";
  final String dummyDrugIngredients =
      "Paracetamol 350 mg, Propyphenazone 150 mg, dan Kafein 50 mg";
  final String dummyDrugDosage = "Dewasa: 1 kaplet, 3x sehari";
  final String dummyDrugTermsofUse = "Dapat dikonsumsi sesudah makan";
}
